<?php

namespace Modules\Leads\Entities;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\Factories\HasFactory;

class PropertyManagementAgreementForm extends Model
{
    use HasFactory;

    protected $fillable = [
        'id',
        'user_id',
        'n_own',
        'bp',
        'form_step',
        'won2_email',
        'fName_1',
        'lName_2',
        'fName_1_2',
        'lName_2_2',
        'own1_identity',
        'own2_identity',
        'located_3',
        'located_o2_3',
        'phone_4',
        'phone_o2_4',
        'email_5',
        'email_o2_5',
        'resident_won1',
        'resident_won2',
        'resident_ca_6',
        'rescount_7',
        'dob_8',
        'tax_sin_no_8',
        'manage_p_at_9',
        'address_10',
        'ad_excess_11',
        'furn_excess_12',
        'IA_rent_13',
        'utilities_14',
        'items_inc_17',
        'parking_17_1',
        'stall_17_2',
        'storage_17_3',
        'others_17_4',
        'pName_18',
        'date_19',
        'pName_20',
        'date_21',
        'w_name_22',
        'reg_own_23',
        'pName_24',
        'date_25',
        'pName_26',
        'date27',
        're_reg_own_28',
        'pw_name_29',
        'ac_holder_30',
        'bank_details_31',
        'pw_name_32',
        'date_33',
        'pw_name_34',
        'date_35',
        'initial_1',
        'initial_2',
        'initial_3',
        'initial_4',
        'initial_5',
        'initial_6',
        'initial_7',
        'initial_8',
        'initial_9',
        'initial_10',
        'initial_11',
        'initial_12',
        'initial_13',
        'initial_14',
        'initial_15',
        'initial_16',
        'initial_17',
        'initial_18',
        'initial_19',
        'initial_20',
        'initial_21',
        'initial_22',
        'initial_23',
        'initial_24',
        'initial_25',
        'AgentN_25',
        'Agentdate_25',
        'voided_check',
        'owner_title',
        'access_token',
        'ip',
        'status',
        'pro_status',
        'notify_status',
        'occu_status',
        'occupancy_tenant_info',
        'agent_pma_id',
        'approved_on',
        'promo_code',
        'promocode',
        'management_type',
        'pma_pdf',
        'referral',
        'referral_other'
    ];

    protected static function newFactory()
    {
        return \Modules\Leads\Database\factories\PropertyManagementAgreementFormFactory::new();
    }
}
